apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic
    app.kubernetes.io/part-of: devfile-sample-go-basic
  name: devfile-sample-go-basic
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/acmenezes-tenant/devfile-sample-go-basic/devfile-sample-go-basic@sha256:cbefedb4ed91119ca5343101a7569714b753be29415daa9b036a1beb42a0a250
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
