apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/acmenezes-tenant/devfile-sample-go-basic/devfile-sample-go-basic@sha256:1c85da3e5070f5bb8089fccb6ceab7f45c3b480fb29447acdbb4a14c5d4dfaa5
        name: my-go
        resources: {}
status: {}
